'''import pandas as pd
import numpy as np

datos = {
    "peso": np.random.uniform(50, 110, 10),
    "estatura": np.random.uniform(1.50, 2.00, 10),
    "salario": np.random.uniform(8000, 40000, 10),
    "edad": np.random.randint(18, 65, 10),
    "pago": np.random.uniform(200, 2000, 10)
}

df = pd.DataFrame(datos)

print("=== TABLA ORIGINAL ===")
print(df, "\n")

df_normalizado = (df - df.min()) / (df.max() - df.min())

print("=== TABLA NORMALIZADA (Min-Max) ===")
print(df_normalizado)
'''


import numpy as np
import requests
from bs4 import BeautifulSoup
from wordcloud import WordCloud, ImageColorGenerator
import matplotlib.pyplot as plt
from PIL import Image

palabras_eliminar = [
    'tan','da','hace','solo','lo','y','se','que','el', 'la', 'los', 'las', 'de', 'y', 'a', 'en', 'un', 'una', 'por', 'para', 'con', 'que','uno','dos',
    'no', 'es', 'como', 'más', 'menos', 'si', 'al', 'las', 'del', 'sobre', 'este', 'esta', 'entre','otro',
    'me', 'te', 'cuando', 'muy', 'también', 'ser', 'yo', 'tú', 'él', 'ella', 'nosotros', 'nosotras','fue',
    'ellos', 'ellas', 'te', 'se', 'ha', 'haber', 'hacer', 'esto', 'estos', 'esas', 'pero', 'o', 'todo',
    'todos', 'cual', 'en', 'con', 'su', 'sus', 'y', 'sí', 'aquel', 'aquella', 'aquellos', 'aquellas', 'mi',
    'mis', 'tu', 'tus', 'su', 'sus', 'nuestro', 'nuestros', 'nuestra', 'nuestras', 'desde'
]

'''
url = input("da página: ")

response = requests.get(url)
if response.status_code == 200:

    soup = BeautifulSoup(response.content, 'html.parser')

    texto = soup.get_text(separator=' ', strip=True)
    texto = texto.lower()

    palabras = texto.split()

    palabras_limpias = [palabra for palabra in palabras if palabra.isalpha() and palabra not in palabras_eliminar]

    texto_limpio = ' '.join(palabras_limpias)
'''
if True:
    texto_limpio = 'BUEN PROFESOR  SABE ENSEÑAR ES BUEN MAESTRO PERO A LA FORMA DE ENSEÑAR NO ES TAN BUENA YA QUE LUEGO NO SE LE ENTIENDE Y TIENES QUE IR CON EL PARA QUE LE ENTIENDAS  NINGUY  EXCELENTE MAESTRO  ME ENCANTARON SUS CLASES  BIEN   NINGUNO ES BUEN MAESTRO Y DA BUENA LAS CLASES  BUEN MAESTRO Y DA TIEMPO A LOS ALUMNOS  ES BUEN MAESTRO ENSEÑA BIEN ME GUSTAN SUS CLASES  BUEN MAESTRO  BUEN DOCENTE  ES BUEN PROFE EXPLICA BIEN  IMPARTE BIEN LA CLASE  NO SE NOS DAN LAS HERRAMIENTAS PARA PROGRAMAR ASI COMO LAS DUDAS QUE SE TENGAN EN CLASE  ES UN BUEN MAESTRO, ME AGRADA COMO DA SUS CLASES Y APRENDI MUY BIEN CON EL  BUEN PROFESOR  BUEN DOCENTE  TIENE MUY BUENOS CONOCIMIENTOS SOBRE LA MATERIA  SABE LO QUE HACE, SIN EMBARGO NO LO SABE EJECUTAR O NO SABE CÓMO EXPLICAR DE MANERA QUE NO SEA TAN DIFÍCIL O ALGO ABURRIDO, A VECES SE PUEDE CONFUNDIR EL MISMO CON LO QUE SE ESTÁ VIENDO Y HACIENDO  EXPLICA MUY BIEN  ESTA DIFÍCIL  ES BUEN MAESTRO  ES BUEN MAESTRO  EXCELENTE PROFESOR  ME ENCANTÓ LA MATERIA  EL DOCENTE DOMINA EL TEMA, EXPLICA CON CLARIDAD Y RESUELVE DUDAS CON BUENA ACTITUD USA EJEMPLOS PRÁCTICOS QUE FACILITAN LA COMPRENSIÓN Y GENERA CONFIANZA EN CLASE  MUY BUENO PERO LE FALTA EXPLICAR UN POQUITO MÁS  MUY BIEN  ES BUENO Y AYUDA EN LO QUE MÁS PUEDA  ME QUEDA MUCHO QUE DESEAR  ES BUENO Y SUS CLASES LAS HACE ENTRETENIDAS, SIENTO QUE NO NECESITA MEJORAR EN NADA  BUEN PROFESOR  ME GUSTA SU FORMA DE ENSEÑAR  EXELENTE MAESTRO  BUEN MAESTRO, PACIENTE PARA EXPLICAR Y ACCESIBLE  MUY BUEN PROFESOR SOLO COMO SUGERENCIA SERÍA QUE ACTUALIZARA SU PROGRAMA DE C++  MUY BUEN PROFESOR, DAN GANAS DE APRENDER MÁS DE LOS TEMAS Y NO SE HACEN ABURRIDOS  BUEN PROFE  DIRECTO AL PUNTO CON EL TEMA Y EXPLICANDO BIEN  AÚN QUE LA MATERIA PUEDA SER DIFÍCIL PUEDES TENER BUENA COMUNICACIÓN CON EL PROFESOR Y SU MANERA DE ENSEÑAR ES MUY BUENA  NO ENTIENDO MUCHO SU CLASE, SOLO SE LA PASA HABLANDO Y HABLANDO Y PARECE QUE EXPLICA SOLO PARA EL  BUEN PROFE, EXPLICA DETALLADAMENTE LOS TEMAS Y LOS CÓDIGOS, HACIENDO QUE NINGUNO SE QUEDE CON DUDAS  EXCELENTE MAESTRO  EXCELENTE MAESTRO  ME ENCANTAN SUS CLASES  ES BUENA ONDA Y TE AYUDA A QUE ENTIENDAS MEJOR  CONOCE MUCHO PERO AHORA LA TEORÍA GANÓ MÁS QUE LA PRÁCTICA Y ASÍ NO ESTÁ BIEN APRENDER  FALTA QUE HAGA SUS CLASES MÁS PREPARADAS    ES UN BUEN DOCENTE Y EXPLICA MUY BIEN  BUEN PROFE TIENE BUEN CONOCIMIENTO DE LA MATERIA  COMPRENDÍ DE MEJOR MANERA EN CADA CÓDIGO QUE HACÍA EN CLASE Y ASÍ SEGUIR MEJORANDO EN LOS CONCEPTOS Y LAS ESTRUCTURAS DE CÓDIGOS DE PROGRAMACIÓN  FUERON TEMAS A MI COMPRESIÓN UN POCO DIFÍCILES PERO CON LOS EJEMPLOS DADOS EN CLASE LE ENTENDÍ A TODO LOS TEMAS Y PUDE REALIZAR LOS EJERCICIOS QUE DEJABA  IGUAL QUE EN FUNDAMENTOS PERO AQUÍ ES MÁS DETALLADO PERO IGUAL QUE SALOMÓN  BUEN FROFE  UN MUY BUEN PROFESOR UNA PERSONA MUY AMABLE  UN MUY BUEN PROFESOR UNA PERSONA MUY AMABLE  ESTA BIEN  EL PEOR PROFESOR DE PROGRAMACIÓN QUE HE TENIDO  ESTA BIEN SE BASA EN LOS CONOCIMIENTOS  BUEN MAESTRO  BIEN MAESTRO  SUPER BUEN PROFESOR HACE QUE SU CLASE SEA MUY INTERESANTE Y ES MUY PUNTUAL  ME GUSTA MUCHO EN LA FORMA QUE NOS EXPLICA Y NOS PASA AL PIZARRÓN ME AGRADA TOMAR SU CLASE  DIOS MÍO, LAS CLASES MÁS ABURRIDAS Y MONÓTONAS QUE HAYA VISTO, SABE EXPLICAR MATES, PERO PROGRAMACIÓN NO  OK  NINGUNO  ENTRE REGULAR Y PÉSIMO ALGUNAS DE SUS CLASES NI SE LE ENTIENDE ,DA MUCHA VUELTA PARA LO QUE ES EXPLICA MUY MAL NO LO TOMARIA NI POR ACREDITACIÓN  PUES ES MUY CONFIANZUDO PERO EXPLICA BIEN  BUEN PROFESOR  ALGO CONFUSO LOS PROGRAMAS  MUY BUENO  BUEN PROFESOR EJERCE MUY BIEN SU TRABAJO  EXCELENTE PROFESOR  NADA  NO SE EXPLICA  DA BIEN LA CLASE Y RESUELVE CUALQUIER DUDA  NI MU MUY NI TAN TAN  ES UN BUEN DOCENTE, LO RECOMIENDO  TODO BIEN  ESTÁ BIEN  BIEN  BIEN  SIGA ASÍ PROFE  SIGA ASI  NINGUNO  EL DOCENTE EXPLICA CON CLARIDAD, DEMUESTRA DOMINIO DEL TEMA Y ES ACCESIBLE  LO MALO ES QUE SE EXPRESA MAL DE LOS ALUMNOS NO LO HACE EN CLASE, PERO SÍ HACE COMENTARIOS NEGATIVOS ES DE POCO HUEVOS HABLAR A ESPALDAS Y OFENDER ASÍ A LOS COMPAÑEROS  SIN COMENTARIOS  EXPLICA EXCELENTE SOLO QUE AVECES METE MUCHO MIEDO  NINGUNO  NO RECOMENDARIA TANTO A ESTE PROFESOR YA QUE EN OCASIONES LOS CODIGOS NO SE SALEN, Y SUS EXPLICACIONES SON MAS CONFUSAS, EN LOS EXAMENES QUIERE QUE SEAN RESUELTOS TAL CUAL EL DICE ASI EL EJERCICIO ESTE BIEN EXIJE MUCHO PARA LO POCO QUE DA  ES UN PROFESOR MUY BUENO  SOLO TE PAQ SI YEW SIENTAS ENFRENTÉ  MUY BUENA CLASE  BUEN PROFESOR EXPLICA MUY BIEN Y ENTENDÍ BIEN  ES BUEN DOCENTE , SIEMPRE EXPLICA DE UNA MANERA MUY CONCISA Y SUS CLASES SON PARCIALMENTE ENTRETENIDAS  NINGUNO  QUE DEBERÍA DE LLEVAR UN POCO LAS EXPLICACIONES MÁS EXTENSAS EN LOS TEMAS, LLEVA MUY RÁPIDO LOS TEMAS Y NO TODOS APRENDEMOS DE LA MISMA FORMA, CREÓ QUÉ DEBERÍA DE PROPORCIONAR SUS DOCUMENTOS DIGITALES PARA UN APRENDIZAJE MEJOR  NO LLEGUE A ENTENDER SU FORMA DE EXPLICAR  BUEN MAESTRO  BUEN MAESTRO  MUY BUENA CLASE Y BUENAAS EXPLICACIONES  MUY BUENA CLASE Y EXCELENTES EXPLICACIONES  BUEN PROFESOR  NINGUNA  EXCELENTE PROFESOR  ENSEÑA MUY BIEN LOS TEMAS Y LOS EXÁMENES JUSTO DE LO QUE NOS ENSEÑÓ  ME PARECIÓ MUY BIEN LA FORMA DE ENSEÑAR DEL PROFESOR  EXCELENTE DOCENTE  MUY BUEN MAESTRO  ME GUSTA SU CLASE Y EXPLICA MUY BIEN  EXCELENTE PROFE  ES UN BUEN MAESTRO ENSEÑA MUY BIEN, NO HACE SUS CLASES TEDIOSAS Y APRENDES MUCHO  BUEN PROFESOR  SABE SOBRE SU MATERIA LE FALTA EMPATIZAR MÁS  FALTA QUE PONGA MÁS EMPEÑO EN SU CHAMBA  ESE WE QUE, NO ENSEÑA NI UN PITO, SE PARECE AL FEDELOBO Y DEJA PROYECTOS COMO SI ENSEÑARÁ  BUEN ROLLO EL PROFE, EXPLICA BIEN  ME GUSTA COMO ENSEÑA :)  GRAN PROFE  :/  BIEN EXPLICADO  BUENAS CLASES  EXCELENTE MAESTRO  ES UN GRAN PROFESOR  DEBERÍA DE INTENTAR EN LABORATORIO SUS PRÁCTICAS AUNQ SE RETRASÉ YA Q ALGUNOS SE ABURREN CON LO TEÓRICO  SABE EXPLICAR LOS TEMAS, PERO A VECES LOS TEMAS QUE EXPLICA LOS PUEDE DAR SOLO UNA VEZ Y PREGUNTAR SOBRE ESO EN UN EXAMEN, CUANDO ESE TEMA NO FUE VISTO TAN EXTENSAMENTE EN CLASES  ES UN MAESTRO MUY BUENO, ME GUSTA LA DINÁMICA QUE EMPLEA EN SUS CLASES COMO PROFESOR LO QUE ME AGRADÓ MÁS DES SUS CLASES ES QUE TE EXPLICA A DETALLE CADA COSA Y TE ENSEÑA COSAS NUEVAS Y COMO LAS PUEDES EMPLEAR  BUEN PROFESOR  EXCELENTE CLASE  EXCELENTE PROFESOR SUMAMENTE ACCESIBLE Y PROFESIONAL, SE NOTA ALTOS CONOCIMIENTO EN LA MATERIA  EL DOCENTE TIENE UNA GRAN HABILIDAD PARA EXPLICAR CONCEPTOS ABSTRACTOS DE MANERA CLARA, ESPECIALMENTE TEMAS COMPLEJOS COMO CONJUNTOS, LÓGICA Y RELACIONES  EL DOCENTE MUESTRA DOMINIO TÉCNICO DEL LENGUAJE DE PROGRAMACIÓN UTILIZADO Y RESPONDE ADECUADAMENTE A LAS DUDAS QUE SURGEN  ENSEÑA BIEM  ENSEÑA BIEM  EL DOCENTE EXPLICA CON CLARIDAD, DEMUESTRA DOMINIO DEL TEMA Y ES ACCESIBLE  ENSEÑA EXCELENTE  ENSEÑA EXELENTE  MUY BUENO  MUY BUEN MAESTRO, APRENDES BIEN  BUEN MAESTRO  BUEN PROFESOR  MUY BUEN PROFESOR  LO MISMO PERO MÁS PAYASO QUE EL DE PROGRAMACIÓN  ENSEÑA MUY BIEN ADEMÁS ES AMABLE AUNQUE A VECES ODIOSO  SABE EXPLICAR LA MATERIA Y AYUDA AL ALUMNO CUANDO TIENE DUDA  TE ENSEÑA LO NECESARIO PARA PODER EMPEZAR LA CARRERA, BUEN PROFE  UN MUY BUEN PROFESOR DE PROGRAMACIÓN AUNQUE CREO QUE HUBIERA SIDO MEJOR HABER TENIDO HORAS EN LABORATORIO PARA PRACTICAR LA SINTAXIS  NINGUNO  NINGUNO'



    texto_limpio = texto_limpio.lower()
    palabras = texto_limpio.split()

    palabras_limpias = [palabra for palabra in palabras if palabra.isalpha() and palabra not in palabras_eliminar]

    texto_limpio = ' '.join(palabras_limpias)

    imagen = Image.open('gokuu.png').convert("RGBA")
    imagen2 = Image.new("RGB", imagen.size, "WHITE")
    imagen2.paste(imagen, (0, 0), imagen)
    # plt.imshow(imagen2)
    mascara = np.array(imagen2)
    colores_mascara = ImageColorGenerator(mascara)

    wordcloud = WordCloud(mask=mascara, contour_width=3, min_font_size=6, contour_color='grey', collocation_threshold=10, width=600,
                          height=300, background_color='white').generate(texto_limpio)

    plt.figure(figsize=(10, 5))

    plt.imshow(wordcloud.recolor(color_func=colores_mascara), interpolation='bilinear')
    plt.axis('off')
    plt.show()

else:
    print(f"No se pudo obtener la página. Código de estado: {response.status_code}")
